# Generated by Django 4.2 on 2024-06-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_edit_description', 'Can edit description'), ('can_edit_category', 'Can edit category'), ('can_canceled_publication', 'Can canceled publication')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
